name: Build Android APK (CubAlquila)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código del Repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Vincular Llave de Firmas para Gradle
      run: |
        # Busca tu archivo .jks actual y crea la copia exacta que build.gradle exige
        REAL_JKS=$(find . -name "*.jks" | head -n 1)
        if [ ! -z "$REAL_JKS" ]; then
          cp "$REAL_JKS" ./my-upload-key.jks
          echo "✔ Llave JKS vinculada correctamente como my-upload-key.jks"
        else
          echo "❌ Error: No se encontró ningún archivo de firma .jks en el proyecto."
          exit 1
        fi

    - name: Conceder Permisos de Ejecución a Gradle
      run: chmod +x ./gradlew

    - name: Compilar APK con Gradle
      run: ./gradlew assembleRelease

    - name: Subir APK Generado a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: CubAlquila-Release-APK
        path: app/build/outputs/apk/release/*.apk
