name: Compilar y Firmar APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código del Repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Configurar Llaves y Propiedades Nativas de Firma
      run: |
        # 1. Encontrar tu llave física real en el proyecto
        REAL_KEY=$(find . -name "taxicuba-identity.jks" | head -n 1)
        echo "Llave real en: $REAL_KEY"
        
        # 2. Crear las copias que Gradle necesita tanto en la raíz como en la carpeta app
        cp "$REAL_KEY" ./my-upload-key.jks
        cp "$REAL_KEY" ./app/my-upload-key.jks
        
        # 3. Inyectar las contraseñas directamente en el archivo global de propiedades de Gradle
        mkdir -p ~/.gradle
        echo "RELEASE_STORE_PASSWORD=Hisa.261199." >> ~/.gradle/gradle.properties
        echo "RELEASE_KEY_PASSWORD=Hisa.261199." >> ~/.gradle/gradle.properties
        echo "RELEASE_STORE_FILE=my-upload-key.jks" >> ~/.gradle/gradle.properties
        echo "RELEASE_KEY_ALIAS=taxicuba-identity" >> ~/.gradle/gradle.properties

    - name: Conceder permisos de ejecución a gradlew
      run: chmod +x ./gradlew

    - name: Compilar APK (Modo Release)
      # Desactivamos el cache para asegurar una lectura limpia de las nuevas propiedades
      run: ./gradlew assembleRelease --no-configuration-cache

    - name: Instalar apksigner en el servidor
      run: sudo apt-get update && sudo apt-get install -y apksigner

    - name: Alinear y Sellar APK Final
      run: |
        # Buscamos la APK generada por la compilación exitosa
        APK_PATH=$(find app/build/outputs/apk/ -name "*.apk" | head -n 1)
        echo "APK base encontrada en: $APK_PATH"
        
        # Forzamos la firma final externa garantizando el nombre CubAlquila.apk
        apksigner sign --ks ./my-upload-key.jks --ks-pass pass:"Hisa.261199." --out CubAlquila.apk "$APK_PATH"

    - name: Subir APK Generado a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: CubAlquila-Descarga
        path: CubAlquila.apk
